# Development-only helpers. Nothing here runs in CI or in a deployment.

DEV_ENV_FILE := .env
DEV_KEY_ID := local-dev

.PHONY: dev-keys
## Generate the local RSA key pair docker-compose.yml reads, into a git-ignored
## .env. The pair is per developer and per machine: it exists so the local stack
## can mint and verify tokens, and it is deliberately not repository material.
dev-keys:
	@if [ -f "$(DEV_ENV_FILE)" ] && [ -z "$(FORCE)" ]; then \
		echo "$(DEV_ENV_FILE) already exists; run 'make dev-keys FORCE=1' to replace it" >&2; \
		exit 1; \
	fi
	@umask 077; \
	key=$$(mktemp); \
	openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$$key" 2>/dev/null || { rm -f "$$key"; echo "openssl failed" >&2; exit 1; }; \
	{ \
		echo "# Generated by 'make dev-keys'. Local development only, git-ignored,"; \
		echo "# and read by docker-compose.yml. Never reuse this key anywhere else."; \
		printf 'IDENTITY_JWT_PRIVATE_KEY="'; cat "$$key"; printf '"\n'; \
		echo 'IDENTITY_JWT_KEY_ID=$(DEV_KEY_ID)'; \
		printf 'IDENTITY_JWT_PUBLIC_KEYS='\''{"$(DEV_KEY_ID)":"'; \
		openssl pkey -in "$$key" -pubout | awk '{ printf "%s\\n", $$0 }'; \
		printf '"}'\''\n'; \
	} > $(DEV_ENV_FILE); \
	rm -f "$$key"; \
	chmod 600 $(DEV_ENV_FILE); \
	echo "wrote $(DEV_ENV_FILE) (mode 600): a fresh key pair under key id $(DEV_KEY_ID)"
